# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cc/hpdic/DIGRA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cc/hpdic/DIGRA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cc/hpdic/DIGRA/CMakeFiles /home/cc/hpdic/DIGRA//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cc/hpdic/DIGRA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named digra_churn

# Build rule for target.
digra_churn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 digra_churn
.PHONY : digra_churn

# fast build rule for target.
digra_churn/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digra_churn.dir/build.make CMakeFiles/digra_churn.dir/build
.PHONY : digra_churn/fast

#=============================================================================
# Target rules for targets named hnsw_churn

# Build rule for target.
hnsw_churn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hnsw_churn
.PHONY : hnsw_churn

# fast build rule for target.
hnsw_churn/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hnsw_churn.dir/build.make CMakeFiles/hnsw_churn.dir/build
.PHONY : hnsw_churn/fast

#=============================================================================
# Target rules for targets named hnsw_reclaim_probe

# Build rule for target.
hnsw_reclaim_probe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hnsw_reclaim_probe
.PHONY : hnsw_reclaim_probe

# fast build rule for target.
hnsw_reclaim_probe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hnsw_reclaim_probe.dir/build.make CMakeFiles/hnsw_reclaim_probe.dir/build
.PHONY : hnsw_reclaim_probe/fast

digra_churn.o: digra_churn.cpp.o
.PHONY : digra_churn.o

# target to build an object file
digra_churn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digra_churn.dir/build.make CMakeFiles/digra_churn.dir/digra_churn.cpp.o
.PHONY : digra_churn.cpp.o

digra_churn.i: digra_churn.cpp.i
.PHONY : digra_churn.i

# target to preprocess a source file
digra_churn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digra_churn.dir/build.make CMakeFiles/digra_churn.dir/digra_churn.cpp.i
.PHONY : digra_churn.cpp.i

digra_churn.s: digra_churn.cpp.s
.PHONY : digra_churn.s

# target to generate assembly for a file
digra_churn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digra_churn.dir/build.make CMakeFiles/digra_churn.dir/digra_churn.cpp.s
.PHONY : digra_churn.cpp.s

hnsw_churn.o: hnsw_churn.cpp.o
.PHONY : hnsw_churn.o

# target to build an object file
hnsw_churn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hnsw_churn.dir/build.make CMakeFiles/hnsw_churn.dir/hnsw_churn.cpp.o
.PHONY : hnsw_churn.cpp.o

hnsw_churn.i: hnsw_churn.cpp.i
.PHONY : hnsw_churn.i

# target to preprocess a source file
hnsw_churn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hnsw_churn.dir/build.make CMakeFiles/hnsw_churn.dir/hnsw_churn.cpp.i
.PHONY : hnsw_churn.cpp.i

hnsw_churn.s: hnsw_churn.cpp.s
.PHONY : hnsw_churn.s

# target to generate assembly for a file
hnsw_churn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hnsw_churn.dir/build.make CMakeFiles/hnsw_churn.dir/hnsw_churn.cpp.s
.PHONY : hnsw_churn.cpp.s

hnsw_reclaim_probe.o: hnsw_reclaim_probe.cpp.o
.PHONY : hnsw_reclaim_probe.o

# target to build an object file
hnsw_reclaim_probe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hnsw_reclaim_probe.dir/build.make CMakeFiles/hnsw_reclaim_probe.dir/hnsw_reclaim_probe.cpp.o
.PHONY : hnsw_reclaim_probe.cpp.o

hnsw_reclaim_probe.i: hnsw_reclaim_probe.cpp.i
.PHONY : hnsw_reclaim_probe.i

# target to preprocess a source file
hnsw_reclaim_probe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hnsw_reclaim_probe.dir/build.make CMakeFiles/hnsw_reclaim_probe.dir/hnsw_reclaim_probe.cpp.i
.PHONY : hnsw_reclaim_probe.cpp.i

hnsw_reclaim_probe.s: hnsw_reclaim_probe.cpp.s
.PHONY : hnsw_reclaim_probe.s

# target to generate assembly for a file
hnsw_reclaim_probe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hnsw_reclaim_probe.dir/build.make CMakeFiles/hnsw_reclaim_probe.dir/hnsw_reclaim_probe.cpp.s
.PHONY : hnsw_reclaim_probe.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... digra_churn"
	@echo "... hnsw_churn"
	@echo "... hnsw_reclaim_probe"
	@echo "... digra_churn.o"
	@echo "... digra_churn.i"
	@echo "... digra_churn.s"
	@echo "... hnsw_churn.o"
	@echo "... hnsw_churn.i"
	@echo "... hnsw_churn.s"
	@echo "... hnsw_reclaim_probe.o"
	@echo "... hnsw_reclaim_probe.i"
	@echo "... hnsw_reclaim_probe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

